services:
  ansible_container:
    build:
      context: ./Docker
      dockerfile: Dockerfile-ansible
    container_name: ansible_container
    volumes:
      - ./ansible:/ansible
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

networks:
  default:
    name: ansible_network