---
- name: Create and configure target container
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Check if target container exists
      shell: docker ps -a --filter name=target_container --format {% raw %}'{{.Names}}'{% endraw %}
      register: container_exists

    - name: Remove existing target container if it exists
      shell: docker rm -f target_container
      when: "'target_container' in container_exists.stdout"

    - name: Create target container
      shell: >
        docker run -d --name target_container
        --network ansible_network
        python:3.9-slim-buster
        sleep infinity

    - name: Wait for target container to be ready
      pause:
        seconds: 10

    - name: Install SSH in target container
      shell: >
        docker exec target_container /bin/sh -c
        "apt-get update && apt-get install -y ssh &&
        mkdir -p /run/sshd &&
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        echo 'root:password' | chpasswd &&
        /usr/sbin/sshd"

    - name: Create a test file in target container
      shell: docker exec target_container /bin/sh -c "echo 'This file was created by Ansible' > /tmp/test_file.txt"

    - name: Display file contents
      shell: docker exec target_container cat /tmp/test_file.txt
      register: file_contents

    - name: Show file contents
      debug:
        var: file_contents.stdout